version: '1.0'
services:
  app:
    image: your-nodejs-app:1.0
    container_name: testapp
    restart: unless-stopped
    ports:
      - "9595:9156"
    volumes:
      - testapp:/app/logs
    environment:
      - TZ=Asia/Karachi
      - NODE_ENV=development
volumes:
  testapp:
